/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface {{cookiecutter.component_class}} {
    'name': string;
  }
  interface {{cookiecutter.component_class}}Attributes extends StencilHTMLAttributes {
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    '{{cookiecutter.component_class}}': Components.{{cookiecutter.component_class}};
  }

  interface StencilIntrinsicElements {
    'my-component': Components.{{cookiecutter.component_class}}Attributes;
  }


  interface HTML{{cookiecutter.component_class}}Element extends Components.{{cookiecutter.component_class}}, HTMLStencilElement {}
  var HTML{{cookiecutter.component_class}}Element: {
    prototype: HTML{{cookiecutter.component_class}}Element;
    new (): HTML{{cookiecutter.component_class}}Element;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTML{{cookiecutter.component_class}}Element
  }

  interface ElementTagNameMap {
    'my-component': HTML{{cookiecutter.component_class}}Element;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
